variable "region"               { type = string }
variable "db_name"              { type = string }
variable "username"             { type = string }
variable "password"             { type = string }
variable "instance_class"       { type = string }
variable "allocated_storage"    { type = number }
variable "engine_version"       { type = string }
variable "subnet_ids"           { type = list(string) }
variable "vpc_security_group_ids"{ type = list(string) }
