version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: sneakrushdb
      POSTGRES_USER: sneakrush
      POSTGRES_PASSWORD: sneakrushpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  redis_2fa:
    image: redis:alpine
    ports:
      - "6380:6379"

volumes:
  pgdata:
  mongodata:
