version: '3.8'

services:
  login_history:
    build: ./BACKEND/domains/user_security/login_history
    environment:
      - DATABASE_URL=postgres://sneakrush:sneakrushpass@34.193.151.166:5432/sneakrushdb?sslmode=disable
      - PORT=4000
    ports:
      - "4000:4000"

  auth_service:
    build: ./BACKEND/domains/user_security/auth_service
    environment:
      - DATABASE_URL=postgresql://sneakrush:sneakrushpass@34.193.151.166:5432/sneakrushdb?sslmode=disable
      - JWT_SECRET=supersecretkey
      - LOGIN_HISTORY_SOAP=http://login_history:4000/logins
      - TWO_FA_URL=http://2fa_service:4002/api/2fa/send
      - TWO_FA_SEND_URL=http://2fa_service:4002/api/2fa/send
    depends_on:
      - login_history
      - 2fa_service
    ports:
      - "3000:3000"

  2fa_service:
    build: ./BACKEND/domains/user_security/2fa_service
    environment:
      - REDIS_URL=redis://34.193.151.166:6380
      - NOTIFICATION_SERVICE=http://notification_service:4003/send
      - PORT=4002
    ports:
      - "4002:4002"

  notification_service:
    build: ./BACKEND/domains/orders_payments/notifications_service
    environment:
      - MONGO_URI=mongodb://34.193.151.166:27017/notificationsdb
      - REDIS_EVENTS_URL=redis://34.193.151.166:6380
      - PORT=4003
    ports:
      - "4003:4003"

  password_recovery:
    build: ./BACKEND/domains/user_security/password_recovery
    environment:
      - DATABASE_URL=postgresql://sneakrush:sneakrushpass@34.193.151.166:5432/sneakrushdb?sslmode=disable
      - RESET_TOKEN_EXP_MINUTES=15
      - NOTIFICATION_SERVICE_URL=http://notification_service:4003/send
      - PORT=4004
    ports:
      - "4004:4004"

  user_service:
    build: ./BACKEND/domains/user_security/user_service
    environment:
      - DATABASE_URL=postgresql://sneakrush:sneakrushpass@34.193.151.166:5432/sneakrushdb?sslmode=disable
      - AUTH_SERVICE_URL=http://auth_service:3000
      - NOTIFICATION_SERVICE_URL=http://notification_service:4003/send
    ports:
      - "4005:8000"
    depends_on:
      - auth_service
      - notification_service

  cart_service:
    image: kevineduardo14/cart_service:latest
    environment:
      - REDIS_URL=redis://34.193.151.166:6380
      - AUTH_SERVICE_URL=http://auth_service:3000
      - CHECKOUT_SERVICE_URL=http://checkout_service:8004
      - PORT=4001
    ports:
      - "4006:4001"
    depends_on:
      - auth_service
      - checkout_service

networks:
  default:
    driver: bridge