openapi: 3.0.0
info:
  title: Category Service API
  version: 1.0.0
paths:
  /categories:
    post:
      summary: Crear categoría
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
      responses:
        '201':
          description: Categoría creada
        '500':
          description: Error