openapi: 3.0.0
info:
  title: Notification Service
  version: "1.0"
  description: Send email/SMS notifications for SneakRush
servers:
  - url: http://localhost:4003
paths:
  /send:
    post:
      summary: Send notification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                to:
                  type: string
                  example: user@sneakrush.com
                message:
                  type: string
                  example: Your verification code is 123456
      responses:
        "200":
          description: Notification accepted
          content:
            application/json:
              schema:
                type: object
                properties:
                  sent:
                    type: boolean