name: 🚧 QA Infra Provisioning

on:
  push:
    branches:
      - qa

jobs:
  terraform:
    name: Terraform Apply QA
    runs-on: ubuntu-latest
    outputs:
      postgres_endpoint: ${{ steps.outputs.outputs.postgres_endpoint }}
      ec2_ip:            ${{ steps.outputs.outputs.ec2_ip }}

    steps:
      - name: Checkout infra
        uses: actions/checkout@v3
        with:
          path: infra/terraform/qa

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Terraform Init
        working-directory: infra/terraform/qa
        run: terraform init

      - name: Terraform Apply
        working-directory: infra/terraform/qa
        env:
          AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: terraform apply -auto-approve

      - id: outputs
        name: Capture Terraform Outputs
        working-directory: infra/terraform/qa
        run: |
          echo "postgres_endpoint=$(terraform output -raw postgres_endpoint)" >> $GITHUB_OUTPUT
          echo "ec2_ip=$(terraform output -raw auth_service_ip)"       >> $GITHUB_OUTPUT
